name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install ruby-bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-bundler
      - name: Cache gems
        id: cache-gems
        uses: actions/cache@v3
        with:
          path: |
            .bundle
            vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install gems
        if: steps.cache-gems.outputs.cache-hit != 'true'
        run: |
          bundle config set --local path vendor/bundle
          bundle install
      - name: Build
        run: bundle exec jekyll build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site/*

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site/
      - name: Deploy site
        run: _releng/deploy.py
